In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [4]:
cat=df.groupby('Category')
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [5]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [6]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [14]:
df.groupby(['Store','Category'])['Sales'].sum()

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

In [15]:
df.describe()

            Sales   Quantity                 Date
count    8.000000   8.000000                    8
mean   187.500000  15.375000  2023-01-04 12:00:00
min    100.000000   8.000000  2023-01-01 00:00:00
25%    142.500000  11.500000  2023-01-02 18:00:00
50%    190.000000  15.000000  2023-01-04 12:00:00
75%    212.500000  18.500000  2023-01-06 06:00:00
max    300.000000  25.000000  2023-01-08 00:00:00
std     66.062741   5.553313                  NaN

In [16]:
df['Sales'].agg(['sum','mean','max','min','count','std'])

sum      1500.000000
mean      187.500000
max       300.000000
min       100.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64