In [ ]:
# Lets begin the Pandas

In [ ]:
pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [8]:
my_list=[10,20,30,40]
arr=np.array([10,20,30,40])
labels=["a","b","c","d"]
d={1:20,2:20,3:30,4:40}

In [6]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [9]:
pd.Series(d)

1    20
2    20
3    30
4    40
dtype: int64

In [10]:
pd.Series(arr)

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [16]:
pd.DataFrame(data_list,index=labels)

       0   1         2      3
a   John  28  New York  65000
b   Anna  34     Paris  70000
c  Peter  29    Berlin  62000
d  Linda  42    London  85000

In [18]:
columns=["name","Age","City","Salary"]
df=pd.DataFrame(data_list,columns=columns)
df

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df[['name','Salary','City']]

    name  Salary      City
0   John   65000  New York
1   Anna   70000     Paris
2  Peter   62000    Berlin
3  Linda   85000    London

In [24]:
df['designation']=['engr','doct','artist','singer']
df

    name  Age      City  Salary designation
0   John   28  New York   65000        engr
1   Anna   34     Paris   70000        doct
2  Peter   29    Berlin   62000      artist
3  Linda   42    London   85000      singer

In [25]:
df

    name  Age      City  Salary designation
0   John   28  New York   65000        engr
1   Anna   34     Paris   70000        doct
2  Peter   29    Berlin   62000      artist
3  Linda   42    London   85000      singer

In [28]:
df.drop("designation",axis=1,inplace=True)

In [29]:
df

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df.drop(0,axis=0)

    name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [42]:
df

    name  Age      City  Salary        4
0   John   28  New York   65000    Adeel
1   Anna   34     Paris   70000       19
2  Peter   29    Berlin   62000  Karachi
3  Linda   42    London   85000    56700

In [43]:
df.drop(4,axis=1,inplace=True)

In [44]:
df

    name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [59]:
df.loc[[1,2]][["name",'City']]

    name    City
1   Anna   Paris
2  Peter  Berlin

In [60]:
df.iloc[3]

name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [64]:
df[(df['Age']>30) & (df['City']=="Paris")]

   name  Age   City  Salary
1  Anna   34  Paris   70000